name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release & publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run full test suite
        run: yarn test:coverage
        env:
          IPLOCATE_API_KEY: ${{ secrets.IPLOCATE_API_KEY }}

      - name: Build package
        run: yarn build

      - name: Generate changelog
        id: changelog
        run: |
          if [ -f "CHANGELOG.md" ]; then
            echo "changelog<<EOF" >> $GITHUB_OUTPUT
            sed -n "/^## \[$(echo $GITHUB_REF_NAME | sed 's/v//')\]/,/^## \[/p" CHANGELOG.md | sed '$d' >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "changelog=Release $GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}

      - name: Publish to npm
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          IPLOCATE_API_KEY: ${{ secrets.IPLOCATE_API_KEY }}
